# Generated by Django 5.1.3 on 2025-10-31 08:15

import Clientes.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del Plan')),
                ('plan_type', models.CharField(choices=[('finde', 'Plan Finde'), ('diario', 'Plan Diario'), ('completo', 'Plan Completo')], max_length=10, unique=True, verbose_name='Tipo de Plan')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio')),
                ('duration_days', models.IntegerField(default=30, verbose_name='Duración en Días')),
                ('access_days', models.CharField(help_text='Ej: Lunes a Viernes, Fines de semana, Todos los días', max_length=100, verbose_name='Días de Acceso')),
                ('includes_classes', models.BooleanField(default=False, verbose_name='Incluye Clases Grupales')),
                ('includes_nutritionist', models.BooleanField(default=False, verbose_name='Incluye Nutricionista')),
                ('benefits', models.TextField(blank=True, help_text='Lista de beneficios separados por comas', null=True, verbose_name='Beneficios')),
                ('is_active', models.BooleanField(default=True, verbose_name='Plan Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RUT')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('role', models.CharField(blank=True, choices=[('admin', 'Administrador'), ('moderador', 'Moderador'), ('socio', 'Socio')], max_length=10, null=True, verbose_name='Rol')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Código QR')),
                ('qr_unique_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='ID Único QR')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active_member', models.BooleanField(default=False, verbose_name='Socio Activo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', related_query_name='customuser', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', related_query_name='customuser', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', Clientes.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('payment_method', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('webpay', 'Webpay')], max_length=15, verbose_name='Método de Pago')),
                ('amount_paid', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Monto Pagado')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activa'), ('expired', 'Vencida'), ('cancelled', 'Cancelada')], default='pending', max_length=10, verbose_name='Estado')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='Clientes.plan', verbose_name='Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('status', models.CharField(choices=[('allowed', 'Permitido'), ('denied', 'Denegado')], max_length=10, verbose_name='Estado')),
                ('denial_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón de Denegación')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clientes.membership', verbose_name='Membresía')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'ordering': ['-timestamp'],
            },
        ),
    ]
